# Generated by Django 4.1.3 on 2022-11-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientregister",
            name="admin_approve",
            field=models.BooleanField(default=False),
        ),
    ]
