# Generated by Django 4.1.3 on 2022-12-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patientregister_admin_approve"),
    ]

    operations = [
        migrations.CreateModel(
            name="patient_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50, null=True)),
                ("lastname", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50, unique=True)),
                ("phoneno", models.PositiveBigIntegerField()),
                ("Dateofbirth", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=100)),
                ("Gender", models.CharField(max_length=100)),
                ("Age", models.PositiveIntegerField()),
                ("Maritalstatus", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=250)),
            ],
        ),
    ]
