# Generated by Django 4.1.3 on 2022-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient_detail",
            old_name="Dateofbirth",
            new_name="Date_of_birth",
        ),
        migrations.RenameField(
            model_name="patient_detail",
            old_name="Maritalstatus",
            new_name="Marital_status",
        ),
        migrations.RemoveField(
            model_name="patient_detail",
            name="phoneno",
        ),
        migrations.AddField(
            model_name="patient_detail",
            name="phone_no",
            field=models.PositiveBigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
