# Generated by Django 4.0.7 on 2022-12-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_dateofbirth_patient_detail_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_medical_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('Martial_status', models.CharField(max_length=50, null=True)),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('blood_type', models.CharField(max_length=50, null=True)),
                ('blood_count', models.CharField(max_length=50, null=True)),
                ('symptoms', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
