# Generated by Django 4.0.7 on 2022-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_detail_send_basic_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_detail',
            name='send_basic_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient_medical_details',
            name='send_medi_lab',
            field=models.BooleanField(default=False),
        ),
    ]
