# Generated by Django 4.0.7 on 2023-01-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_lab_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='test_date',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
