# Generated by Django 4.0.7 on 2023-02-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_lab_test_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_test',
            name='test_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
