# Generated by Django 4.0.7 on 2023-02-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_lab_test_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='output',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
