# Generated by Django 4.0.2 on 2023-02-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_lab_test_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
