# Generated by Django 4.0.2 on 2023-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_lab_test_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='send2',
            field=models.BooleanField(default=False),
        ),
    ]
