# Generated by Django 4.0.2 on 2023-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_patient_detail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='second_approve',
            field=models.BooleanField(default=False),
        ),
    ]
