# Generated by Django 4.1.3 on 2022-11-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="doctor_model",
            new_name="doctorRegister",
        ),
    ]
