# Generated by Django 4.1.3 on 2022-11-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_rename_doctor_model_doctorregister"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorregister",
            name="admin_approve",
            field=models.BooleanField(default=False),
        ),
    ]
