# Generated by Django 4.1.3 on 2022-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="lapRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("phoneno", models.PositiveBigIntegerField()),
                ("Dateofbirth", models.CharField(max_length=30)),
                ("Address", models.CharField(max_length=100)),
                ("approve_lab", models.BooleanField(default=False)),
            ],
        ),
    ]
